### PR TITLE
readme: correct pip install list

### LINKED ISSUE #6: README.md: env questions
Just wondering if the following virtual environment command may be preferable to the one in the README.md?  I understand virtualenv is now built into python3 (as `venv`).   On a Ubuntu18.04 LTS system, `python` is actually python2, so running the commands in the README.md resulted in a python 2 environment.  I figured that was going to end badly, and in backing up, discovered this alternate method:

```
$ python3.6 -m venv --system-site-packages env
```

Also, maybe it would be better to tell people to use `_env` or `_sphinx_env`, add it to a "clean" or "veryclean" make target, and to .gitignore to underscore that it's not part of the project?

### PR DESCRIPTION
**Pull request by gonsie**
closes #6

I've left out any specific virtualenv stuff and instead point users at some web documentation.

### CODE REVIEW

**Comment by garlick** [comment]
Thanks!  Sounds good.

**Comment by SteVwonder** [comment]
@gonsie: do you mind rebasing this PR onto master?  That should pull in the new github action to validate commits.  I'm interested to see if that actually works.  I forgot that we don't have travis ci setup on this repo yet, so unfortunately the mergify bot won't be able to auto-merge quite yet (with the current config).

**Comment by gonsie** [comment]
@SteVwonder I think that did it?

**Comment by grondo** [comment]
>  I forgot that we don't have travis ci setup on this repo yet, so unfortunately the mergify bot won't be able to auto-merge quite yet (with the current config).

Ugh. Sorry I didn't notice that when I reviewed your PR @SteVwonder!

**Comment by SteVwonder** [comment]
Thanks @gonsie! That did the trick.

> Ugh. Sorry I didn't notice that when I reviewed your PR @SteVwonder!

No worries.  I was the one that didn't notice it while making the PR, even after you rightly pointed out the missing github action. 🤦‍♂

**Pull request merged**
